#ifndef SWWNS_H
#define SWWNS_H

#define SWW_NAMESPACE_BEGIN_DEF(name) namespace name {
#define SWW_NAMESPACE_END_DEF }

#define SWW_NAMESPACE_BEGIN SWW_NAMESPACE_BEGIN_DEF(Sww)
#define SWW_NAMESPACE_END SWW_NAMESPACE_END_DEF

#endif // SWWNS_H
