#ifndef SWWNSCORE_H
#define SWWNSCORE_H

#include "SwwNs.h"

#define SWW_CORE_NAMESPACE_BEGIN SWW_NAMESPACE_BEGIN SWW_NAMESPACE_BEGIN_DEF(Core)
#define SWW_CORE_NAMESPACE_END SWW_NAMESPACE_END_DEF SWW_NAMESPACE_END_DEF

#endif // SWWNSCORE_H
