#ifndef SWWNSUTIL_H
#define SWWNSUTIL_H
#include "SwwNs.h"

#define SWW_UTIL_NAMESPACE_BEGIN SWW_NAMESPACE_BEGIN_DEF(Sww) SWW_NAMESPACE_BEGIN_DEF(Util)
#define SWW_UTIL_NAMESPACE_END SWW_NAMESPACE_END_DEF SWW_NAMESPACE_END_DEF

#endif // SWWNSUTIL_H
